name: limewire
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pymongo
  - pretty_midi
  - mido
  - selenium
  - beautifulsoup4
  - requests
  - fastapi
  - pydantic
  - uvicorn
  - pip:
      - dotenv
      - librosa
      - mcp